# Generated by Django 4.1.1 on 2022-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0004_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='usd', max_length=10)),
            ],
        ),
    ]
