# Generated by Django 4.1.1 on 2022-09-16 14:32

from django.db import migrations, models

from APIStripe.models import CurrencyItem

CURRENCIES = [
    "usd", "aed", "afn", "all", "amd", "ang", "aoa", "ars", "aud", "awg", "azn", 
    "bam", "bbd", "bdt", "bgn", "bif", "bmd", "bnd", "bob", "brl", "bsd", "bwp", 
    "byn", "bzd", "cad", "cdf", "chf", "clp", "cny", "cop", "crc", "cve", "czk", 
    "djf", "dkk", "dop", "dzd", "egp", "etb", "eur", "fjd", "fkp", "gbp", "gel", 
    "gip", "gmd", "gnf", "gtq", "gyd", "hkd", "hnl", "hrk", "htg", "huf", "idr", 
    "ils", "inr", "isk", "jmd", "jpy", "kes", "kgs", "khr", "kmf", "krw", "kyd", 
    "kzt", "lak", "lbp", "lkr", "lrd", "lsl", "mad", "mdl", "mga", "mkd", "mmk", 
    "mnt", "mop", "mro", "mur", "mvr", "mwk", "mxn", "myr", "mzn", "nad", "ngn", 
    "nio", "nok", "npr", "nzd", "pab", "pen", "pgk", "php", "pkr", "pln", "pyg", 
    "qar", "ron", "rsd", "rub", "rwf", "sar", "sbd", "scr", "sek", "sgd", "shp", 
    "sll", "sos", "srd", "std", "szl", "thb", "tjs", "top", "try", "ttd", "twd", 
    "tzs", "uah", "ugx", "uyu", "uzs", "vnd", "vuv", "wst", "xaf", "xcd", "xof", 
    "xpf", "yer", "zar", "zmw"]

def add_currently(model, currency):

    if not CurrencyItem.objects.filter(currency=currency).exists():
        return model.objects.create(currency=currency)

    return True

def add_currencies_default(apps, schema_editor):

    model = apps.get_model("APIStripe", "CurrencyItem")

    for currently in CURRENCIES:
        add_currently(model, currently)


    result = True

class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0005_currencyitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyitem',
            name='currency',
            field=models.CharField(default='usd', max_length=9),
        ),

        migrations.RunPython(add_currencies_default, reverse_code=migrations.RunPython.noop),
    ]
