# Generated by Django 4.1.1 on 2022-09-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0006_alter_currencyitem_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APIStripe.currencyitem'),
        ),
    ]
