# Generated by Django 4.1.1 on 2022-09-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIStripe', '0007_item_currency_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency_payment',
        ),
    ]
