# Generated by Django 4.1.1 on 2022-09-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesitem',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favoritesitem',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favoritesitem',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
