# Generated by Django 4.1.1 on 2022-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favoritesitem_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritesitem',
            name='count',
        ),
        migrations.RemoveField(
            model_name='favoritesitem',
            name='product_id',
        ),
        migrations.AddField(
            model_name='favoritesitem',
            name='products_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
