# Generated by Django 4.1.1 on 2022-09-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_remove_favoritesitem_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesitem',
            name='products_id',
            field=models.TextField(default=''),
        ),
    ]
