# Generated by Django 4.1.1 on 2022-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_alter_favoritesitem_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritesitem',
            name='products_id',
            field=models.JSONField(null=True),
        ),
    ]
