# Generated by Django 4.1.1 on 2022-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_usercustom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBanIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('attempts', models.IntegerField(default=0, verbose_name='Failed attempts')),
                ('time_unblock', models.DateTimeField(blank=True, verbose_name='Time ban')),
                ('status', models.BooleanField(default=False, verbose_name='Status ban')),
            ],
        ),
    ]
