# Generated by Django 4.1.1 on 2022-09-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyitem',
            name='session_id',
        ),
    ]
