# Generated by Django 4.1.1 on 2022-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_historyitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyitem',
            name='status',
            field=models.CharField(default='expectation', max_length=20),
        ),
    ]
